management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      base-path: /actuator #端点访问前缀 | endpoint access prefix
      exposure:
        include: '*' #暴露所有端点，生产暴露需要注意include配置或者更换管理端口） |
  server:
    port: 8081